### PR TITLE
update signup page to use Jekyll variables

### PR DESCRIPTION
**Pull request by MoralCode**

### CODE REVIEW

**Comment by EnneNerdyPerson** [comment]
The website no longer really uses the signup.html file. The code you changed would need to be moved onto the helloworld.html file instead for it to show up on the website

**Comment by MoralCode** [comment]
Was that page meant to be removed then? It's still live on https://bitbybitcoding.org/signup and also linked to in https://bitbybitcoding.org/sitemap.xml, meaning google will probably index it.

**Comment by MoralCode** [comment]
Screenshot_20200915_085324

**Comment by MoralCode** [comment]
also the donate page was just updated in #105

**Comment by sophiaaaaa** [comment]
oh I can try the plugin

**Comment by MoralCode** [comment]
Superseded by #106

**Pull request closed without merging**
