### PR TITLE
replace logo pngs with svgs

### PR DESCRIPTION
**Pull request by sophiaaaaa**

### CODE REVIEW

**Comment by EnneNerdyPerson** [comment]
The logo looks way better but the font has changed. Was the font change intentional?

**Comment by sophiaaaaa** [comment]
I think I changed it from nunito bold to extra bold

**Comment by Form-And-Function** [comment]
The font is no longer Nunito. @sophiaaaaa can yo follow the instructions here? https://graphicdesign.stackexchange.com/questions/27238/preserving-font-type-in-illustrator-svg-file

**Comment by sophiaaaaa** [comment]
thanks for letting me know! I just fixed them

**Review by Form-And-Function — APPROVED** [review]

**Pull request merged**
